---
title: "week9"
format: html
---

```{r}
# Install Packages

install.packages("rpart")
install.packages("rpart.plot")

```

```{r}
# Load packages

library(sf) # vector data
library(terra) # raster data
library(here) # file path management
library(tidyverse)
library(rpart) # recursive partitioning and regression trees
library(rpart.plot) # plotting for rpart
library(tmap) # map making




```

### Load Landsat data
```{r}
# Create a raster stack of files


# list files for each band, including the full file path
filelist <- list.files(here::here("data", "landsat-data"), full.names = TRUE)

# read in and store as a raster stack
landsat <- rast(filelist)

# update layer names to match band
names(landsat) <- c("blue", "green", "red", "NIR", "SWIR1", "SWIR2")

# plot true color image
plotRGB(landsat, r = 3, g = 2, b = 1, stretch = "lin") # stretch changes axis

```

### Load study area
```{r}
# Crop to study area

# read in shapefile for southern portion of SB county
SB_county_south <- st_read(here::here("data", "SB_county_south.shp")) %>%
      st_transform(SB_county_south, crs = crs(landsat))

tm_shape(SB_county_south) +
  tm_borders()

```

### Crop and mask Landsat data to study area
```{r}
# crop Landsat scene to the extent of the SB county shapefile
landsat_cropped <- crop(landsat, SB_county_south) # cropping cuts out all pixels from original raster file

# mask the raster to southern portion of SB county
landsat_masked <- mask(landsat_cropped, SB_county_south) # mask keeps grid cells outside of extent

# remove unnecessary object from environment
rm(landsat, SB_county_south, landsat_cropped)

plotRGB(landsat_masked, r = 3, g = 2, b = 1, stretch = "lin")


```

### Convert Landsat values to relflectance

```{r}
# reclassify erroneous values as NA; rcl = reclassification matrix; use scaling factor values
rcl <- matrix(c(-Inf, 7273, NA,
                 43636, Inf, NA), ncol = 3, byrow = TRUE)

landsat <- terra::classify(landsat_masked, rcl = rcl)

# adjust values based on scaling factor
landsat <- (landsat * 0.0000275 - 0.2) * 100

# check values are 0 - 100
summary(landsat)



```

### Training classifier

```{r}
# read in and transform training data
training_data <- st_read(here::here( "data", "trainingdata.shp")) %>%
  st_transform(., crs = crs(landsat))

```

```{r}
# extract reflectance values at training sites; from each grid cell
training_data_values <- terra::extract(landsat, training_data, df = TRUE)

# convert training data to data frame
training_data_attributes <- training_data %>%
  st_drop_geometry()

# join training data attributes and extracted reflectance values
SB_training_data <- left_join(training_data_values, training_data_attributes,
                              by = c("ID" = "id")) %>%
                    mutate(type = as.factor(type)) # convert landcover type to factor


```


```{r}
# establish model formula
SB_formula <- type ~ red + green + blue + NIR + SWIR1 + SWIR2

# train decision tree
SB_decision_tree <- rpart(formula = SB_formula,
                          data = SB_training_data,
                          method = "class",
                          na.action = na.omit)

# plot decision tree
prp(SB_decision_tree)

```

### Classify image
```{r}

# classify image based on decision tree
SB_classification <- terra::predict(landsat, SB_decision_tree, type = "class", na.rm = TRUE)

# inspect level to understand the order of classes in prediction
levels(SB_training_data$type)

```


### Plot Restults

```{r}
# plot results
tm_shape(SB_classification) +
  tm_raster(palette = c("#8DB580", "#F2DDA4", "#7E8987", "#6A8EAE"),
labels = c("green vegetation", "soil/dead grass", "urban", "water"),
title = "Landcover type") +
  tm_layout(legend.position = c("left", "bottom"),
            main.title = "Santa Barbara Landcover")
```


